source 'https://rubygems.org'

gem 'sinatra', '~> 1.4', '>= 1.4.7', require: 'sinatra/base'
gem 'bundler', '~> 1.12', '>= 1.12.5'
gem 'json', '~> 2.0', '>= 2.0.1'
gem "rake"
gem "sinatra-activerecord", require: 'sinatra/activerecord'
  
group :development do  
  gem 'sqlite3', '~> 1.3', '>= 1.3.11'   
end

