source 'https://rubygems.org'

# public dependencies
gem 'bundler', '~> 1.12', '>= 1.12.5'
gem 'sinatra', '~> 1.4', '>= 1.4.7', require: 'sinatra/base'

group :development do
  gem 'rerun', '~> 0.11.0'  
end
