source 'https://rubygems.org'

gem 'bundler', '~> 1.12', '>= 1.12.5'
gem 'sinatra', '~> 1.4', '>= 1.4.7', require: 'sinatra/base'
gem 'json', '~> 2.0', '>= 2.0.1'


group :development do
    gem 'rerun', '~> 0.11.0'
end
