source 'https://rubygems.org'

gem 'bundler', '~> 1.12', '>= 1.12.5'
gem 'sinatra', '~> 1.4', '>= 1.4.7', require: 'sinatra/base'
gem 'json'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.9'


group :development do
  gem 'rerun', '~> 0.11.0'
  gem 'sqlite3', '~> 1.3', '>= 1.3.11'
end
