# Require rake tasks
require 'sinatra/activerecord/rake'

# Connect to the database
ActiveRecord::Base.establish_connection(
    :adapter => 'sqlite3',
    :database => 'db.sqlite3'
  )


# Rake Tasks
# set environment
desc "Set up the environment"
task :environment do
  ENV['RACK_ENV'] ||= 'development'
end


# server start, and run the dependent tasks first
namespace :server do
  desc "Start the server"
  task :start => [:environment] do
    exec "rerun rackup"
  end
end

